spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 2s # 파일 변경 감지 간격
      quiet-period: 1s # 변경 후 안정화 대기 시간
    livereload:
      enabled: true
      port: 35729 # LiveReload 포트
  application:
    name: schoolmate
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolmate
    username: javadb
    password: 12345
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  # profiles:
  #   include: oauth
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
com:
  example:
    schoolmate:
      upload:
        path: /Users/hyeonwoo/Desktop/backend/upload
